server:
  port: 8080

spring:
  application:
    name: Chat-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: YOUR_DB_PASSWORD
  rabbitmq:
    port: 5672
    virtual-host:
    password: YOUR_RABBITMQ_PASSWORD
    host: localhost
    username: guest
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1000
        max-interval: 10000
        multiplier: 2
        max-retries: 3
    publisher-confirm-type: correlated
    publisher-returns: true
    connection-timeout: 1s
    listener:
      simple:
        default-requeue-rejected: false
  data:
    aliyun:
      endpoint: dypnsapi.aliyuncs.com
      sign-name: 速通互联验证码
      template-code: 100001
      template-param: '{"code":"##code##","min":"5"}'
      code-type: 1
      valid-time: 120
      code-length: 6
      access-key-id: YOUR_ALIYUN_ACCESS_KEY_ID
      access-key-secret: YOUR_ALIYUN_ACCESS_KEY_SECRET
      bucket-name: summit-chat
      endpointForOss: oss-cn-beijing.aliyuncs.com
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8        # 最大活跃连接数
          max-idle: 8          # 最大空闲连接数
          min-idle: 2          # 最小空闲连接数
          max-wait: 3000ms     # 连接池耗尽时的等待时间（-1表示无限等待）



socket:
  io:
    port: 9090


livekit:
  secret: YOUR_LIVEKIT_SECRET
  apiKey: YOUR_LIVEKIT_API_KEY


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.summit.chat
  configuration:
      map-underscore-to-camel-case: true

# Swagger配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.summit.chat

logging:
  level:
    org.springframework.security: DEBUG  # 打印授权、拦截的详细日志
    org.springframework.web: INFO
    org.springdoc: DEBUG  # 启用springdoc日志
    org.slf4j: DEBUG

rsa:
  private-key: "MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCI3nyTuHdGTe9iQhon4uctH6FmtQJZF0ynq1HFEWfBCjDnrtx43LCSUBHrfYykD+ZQ1RFg0H7Ex4J4eZgkDBQo+R9uCXEZz4DT/5d6xq+xFqcKtIvMINd/2dY4XB2ALGcAuRE7kGddLCa3AnIfOq88FDifylBYuegKSN7qf9kNB4YtWk0nTGd8opAWbx1Wr3rCUhjDFsLC6NoLpyD0m0Dbe1daN2fOO3gFGKfGGvEt8oun5S+CiyBKabLep88RHbox2lMr98bP9lsCWISZrGkK/PQQz2mQQxbiSzHX9hEd9VhodcnwNzC9MZ2qPnByPJ230A18CvfDLFo87ZtyoKZ1AgMBAAECgf8MB4HrecsB4tenSygBWW/4B0+oN0B9lA6oreYB7AWycbLaqgO2m67pLSBmEiLKSJt1f0SHvctmgCJ3dDhq8qTS9RJOGYZXPmWUPGKT5+KJLfSAfF3NExXdpsetLGtrWHu1FI7vLUHobnj4nL5rAD1mimBvqthk8/Hw9XaiJZpuCppY+ExRxB1DIhN99m4Re+1lxptrVLU4kRsC0hdrvNNPUjlAOZPsabeqr6iLVEjdkKFM7RXu49d7QwOB/kzPjWYFMrQ/sWjFI9u+e8WByONv9S8anop/af33fOhAZs+K5kl0Binexs1OXPvsrE0FZQiQ/iionxCrH37ilMZl4TECgYEAu9+xXUeExSyKiJtXezZB5YUcT0qwD/ss3fUrkepKxQdwD7uHIpo8DPJJxKFZ7sJ61lADTf8kWWIOEnii06a4ty9sBHME6/5OpUSG7in5OnMIOsytWhjvyS9Wpc6YfqT7GQbf557DND9trxrr71grBXfk4HsNLmIfAuldCd+BLK0CgYEAuoAH/aYpGXUZ3jwS1PmVdHPJpR4Vm29Gfgvx2+/QhqqNvkRAcQaXaiqpDghzT9lEjw1Jk3hM5NBsv3cBeszJB98y3YybuRsMpf4yHxQJtJm0w/EJp7wah/HCx+O34sCKaODkMypP5MuHvcZsYnLdxjQ98mQ0IRqlEverMRnlkekCgYABdBKQMSxyxgxwUBtWJa5O0z/L0T0Zcoz/TpU+tLxNV+hjBsVd3CmYxAsUDVd/xFtk6wuLf+zNEDghpnNEBecp66D/S9B+7uG235fXodV+wUMQCWNR7h10xfv6nmWJnUcgA3CZ/x1tewwjLacjm+ABU9MedXU9pZ6tzBZfLC54pQKBgQCE+k84S6bYcQedzwW6d69aFkk8A4RyjNgdfdTY9lif/LIObUnpjUKfP4XE7L+Tup5Ixbelf8yMBhTUPD2A2s2oYDw7fkt2o9PT87i3MiltbX9XiuFQiS39qqMwtazi8FiASYJM/Sl0QK8r4HRdifuZnJxi3ZHR3NbA/HlDDG0FKQKBgHL/GIxLUAWYo88tU315vd0kjnhsHZeRuH1v6R9IbYGqBg+h2lYFL9oKH895nvERp6Jf8+PRJ8eQhHvs7WRefNxHftXJfEzUHZG7luDsHGA/1XTjHlc5jJM24EzdnARXMPjk08F41+lAh+mnwKlU3Ia3uDyVy12bF5JQIrIbpY77"
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiN58k7h3Rk3vYkIaJ+LnLR+hZrUCWRdMp6tRxRFnwQow567ceNywklAR632MpA/mUNURYNB+xMeCeHmYJAwUKPkfbglxGc+A0/+XesavsRanCrSLzCDXf9nWOFwdgCxnALkRO5BnXSwmtwJyHzqvPBQ4n8pQWLnoCkje6n/ZDQeGLVpNJ0xnfKKQFm8dVq96wlIYwxbCwujaC6cg9JtA23tXWjdnzjt4BRinxhrxLfKLp+UvgosgSmmy3qfPER26MdpTK/fGz/ZbAliEmaxpCvz0EM9pkEMW4ksx1/YRHfVYaHXJ8DcwvTGdqj5wcjydt9ANfAr3wyxaPO2bcqCmdQIDAQAB"